Rails.application.routes.draw do
  get 'events/index'
  get 'events/new'
  get 'events/create'
  get 'events/show'
  get 'index/new'
  get 'index/create'
  get 'index/show'
  get 'sessions/new'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  resources :users
  root 'users#new'
end
